dbt_on_pg:
  outputs:
    dev:
      dbname: ny_taxi
      host: localhost
      pass: root
      port: 5432
      schema: taxi_data_schema
      threads: 1
      type: postgres
      user: root
  target: dev